@baseUrl = https://localhost:5001

### release_versioning_TestCasesSwaggerReleaseVersioningEndpointA
GET {{baseUrl}}/api/release-versioning/endpoint-a
Accept: application/json


### release_versioning_TestCasesSwaggerReleaseVersioningEndpointB
GET {{baseUrl}}/api/release-versioning/endpoint-b
Accept: application/json


