using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace FastEndpoints.Generator.Cli;

partial class Program
{
    private static void WriteGeneratedOutput(string outputDir,
                                             string projectPath,
                                             string projectName,
                                             HashSet<string> serializableTypes,
                                             GeneratorCacheState cacheState,
                                             string cacheFilePath,
                                             bool includeTimestamp)
    {
        Directory.CreateDirectory(outputDir);

        var rootNamespace = GetRootNamespace(projectPath) ?? projectName.Sanitize();
        var contextCode = GenerateSerializerContext(rootNamespace, serializableTypes, includeTimestamp);
        var contextPath = Path.Combine(outputDir, "SerializerContexts.g.cs");
        File.WriteAllText(contextPath, contextCode, Encoding.UTF8);

        var extensionCode = GenerateExtensionMethod(rootNamespace);
        var extensionPath = Path.Combine(outputDir, "SerializerContextExtensions.g.cs");
        File.WriteAllText(extensionPath, extensionCode, Encoding.UTF8);

        File.WriteAllText(cacheFilePath, JsonSerializer.Serialize(cacheState));

        Console.WriteLine("Generated files:");
        Console.WriteLine($"  {contextPath}");
        Console.WriteLine($"  {extensionPath}");
    }

    private static string GenerateSerializerContext(string rootNamespace, HashSet<string> types, bool includeTimestamp)
    {
        var b = new StringBuilder();

        b.l("// <auto-generated />");
        b.l("// Generated by FastEndpoints.Generator.Cli");

        if (includeTimestamp)
            b.l($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");

        b.l("");
        b.l("#pragma warning disable");
        b.l("#nullable enable");
        b.l("");
        b.l("using System.Text.Json.Serialization;");
        b.l("");
        b.l($"namespace {rootNamespace};");
        b.l("");
        b.l("/// <summary>");
        b.l($"/// STJ serializer context for {rootNamespace} endpoints.");
        b.l("/// </summary>");

        var usedTypeInfoNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var type in types.OrderBy(t => t))
        {
            var globalStrippedType = type.StartsWith("global::", StringComparison.Ordinal) ? type[8..] : type;
            var typeInfoName = MakeTypeInfoPropertyName(type);
            var suffix = 1;

            while (!usedTypeInfoNames.Add(typeInfoName))
                typeInfoName = $"{MakeTypeInfoPropertyName(type)}_{ComputeStableShortHash(type + suffix++)}";

            b.l($"[JsonSerializable(typeof({globalStrippedType}), TypeInfoPropertyName = \"{typeInfoName}\")]");
        }

        b.l("internal partial class GeneratedSerializerContext : JsonSerializerContext;");

        return b.ToString();
    }

    private static string MakeTypeInfoPropertyName(string fullTypeName)
    {
        if (string.IsNullOrWhiteSpace(fullTypeName))
            return "TI_Unknown";

        var dotIndex = fullTypeName.LastIndexOf('.');
        var simpleName = dotIndex >= 0 ? fullTypeName[(dotIndex + 1)..] : fullTypeName;
        simpleName = simpleName.Sanitize();

        var hash = ComputeStableShortHash(fullTypeName);

        return $"TI_{simpleName}_{hash}";
    }

    private static string ComputeStableShortHash(string value)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(value));

        return Convert.ToHexString(bytes, 0, 4);
    }

    private static string GenerateExtensionMethod(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.l("// <auto-generated />");
        sb.l("// Generated by FastEndpoints.Generator.Cli");
        sb.l("");
        sb.l("#pragma warning disable");
        sb.l("#nullable enable");
        sb.l("");
        sb.l("using System.Text.Json;");
        sb.l("");
        sb.l($"namespace {rootNamespace};");
        sb.l("");
        sb.l("/// <summary>");
        sb.l("/// Extension methods for adding generated serializer contexts.");
        sb.l("/// </summary>");
        sb.l("internal static class FastEndpointsSerializerExtensions");
        sb.l("{");
        sb.l("    /// <summary>");
        sb.l("    /// Adds the generated JSON serializer context to the JSON serializer options.");
        sb.l("    /// </summary>");
        sb.l($"    internal static JsonSerializerOptions AddSerializerContextsFrom{rootNamespace}(this JsonSerializerOptions options)");
        sb.l("    {");
        sb.l("        var context = new GeneratedSerializerContext(new(options));");
        sb.l("        options.TypeInfoResolverChain.Insert(0, context);");
        sb.l("");
        sb.l("        return options;");
        sb.l("    }");
        sb.l("}");

        return sb.ToString();
    }
}