trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .Net Core SDK 7.x"
    inputs:
      packageType: "sdk"
      version: "7.x"
      includePreviewVersions: false

  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: "test"
      projects: "**/*[Tt]ests/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"
      workingDirectory: "Tests"

  # - task: DotNetCoreCLI@2
  #   displayName: "Make Nuget Package"
  #   inputs:
  #     command: "pack"
  #     packagesToPack: "Src/**/*.csproj"
  #     versioningScheme: "off"
  #     verbosityPack: "Minimal"

  # - task: NuGetCommand@2
  #   displayName: "Publish To Nuget"
  #   inputs:
  #     command: "push"
  #     packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
  #     nuGetFeedType: "external"
  #     publishFeedCredentials: "nuget-djnitehawk"
