@MinimalAPIWithOData_HostAddress = http://localhost:5000


GET {{MinimalAPIWithOData_HostAddress}}/odata/customers/fastendpoints?top=1
Accept: application/json

###

GET {{MinimalAPIWithOData_HostAddress}}/odata/customers/fastendpoints?$filter=startswith(name,%20%27Michael%27)
Accept: application/json

###

GET {{MinimalAPIWithOData_HostAddress}}/odata/customers/fastendpoints?$filter=name%20eq%20%27John%20Doe%27

###