<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <NoWarn>CS1591</NoWarn>
        <Description>RabbitMQ transport for FastEndpoints commands and events.</Description>
        <IsAotCompatible>false</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Messaging.Core\FastEndpoints.Messaging.Core.csproj"/>

        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
        <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All"/>
        <PackageReference Include="RabbitMQ.Client"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" Link="Content\Icon" Visible="false"/>
    </ItemGroup>

</Project>
